let currentLang = localStorage.getItem('lang') || 'ar';
let currentAccount = localStorage.getItem('currentAccount') || 'main';
let darkMode = localStorage.getItem('darkMode') === 'true';
let appData = JSON.parse(localStorage.getItem('appData')) || {};
if(!appData[currentAccount]) appData[currentAccount] = {tasks:[], finance:[], interceptors:[]};
function saveData(){localStorage.setItem('appData', JSON.stringify(appData));}
function translateApp(){const elements=document.querySelectorAll('[data-translate]');elements.forEach(el=>{const key=el.getAttribute('data-translate');if(translations[currentLang][key])el.textContent=translations[currentLang][key];});document.documentElement.lang=currentLang;document.documentElement.dir=currentLang==='ar'?'rtl':'ltr';}
const translations={ar:{app_title:"مخططي اليومي",daily_view:"اليومي",weekly_view:"الأسبوعي",monthly_view:"الشهري (التقويم)",finance:"المالية",analytics:"التحليلات",archive:"الأرشيف التاريخي",settings:"الإعدادات",today_plan:"خطة اليوم",week_plan:"خطة الأسبوع",month_plan:"تقويم الشهر",finance_tracker:"المتتبع المالي",analytics_dashboard:"لوحة التحليلات",history_archive:"الأرشيف التاريخي",settings_menu:"الإعدادات",export:"تصدير البيانات",import:"استيراد البيانات",sync:"مزامنة سحابية",income:"وارد",expense:"مصروف",daily_progress:"تقدم اليوم"},en:{app_title:"My Daily Planner",daily_view:"Daily",weekly_view:"Weekly",monthly_view:"Monthly (Calendar)",finance:"Finance",analytics:"Analytics",archive:"History Archive",settings:"Settings",today_plan:"Today's Plan",week_plan:"Week Plan",month_plan:"Month Calendar",finance_tracker:"Finance Tracker",analytics_dashboard:"Analytics Dashboard",history_archive:"History Archive",settings_menu:"Settings",export:"Export Data",import:"Import Data",sync:"Cloud Sync",income:"Income",expense:"Expense",daily_progress:"Daily Progress"},am:{app_title:"የእኔ ዕቅድ",daily_view:"በቀን",weekly_view:"በሳምንት",monthly_view:"በወር",finance:"ፋይናንስ",analytics:"ትንተና",archive:"የታሪክ ማከማቻ",settings:"ቅንብሮች",today_plan:"የዛሬ ዕቅድ",week_plan:"የሳምንት ዕቅድ",month_plan:"የወር ቀን መቁጠሪያ",finance_tracker:"የገንዘብ መከታተያ",analytics_dashboard:"የትንተና ዳሽቦርድ",history_archive:"የታሪክ ማከማቻ",settings_menu:"ቅንብሮች",export:"መረጃ ላክ",import:"መረጃ አምጣ",sync:"ደመና ማመሳሰያ",income:"ገቢ",expense:"ወጪ",daily_progress:"የዛሬ እድገት"}};
document.addEventListener('DOMContentLoaded',()=>{
if(darkMode)document.body.classList.add('dark-mode');
translateApp();
document.getElementById('loading-screen').style.display='none';
document.getElementById('toggle-sidebar').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('active'));
document.getElementById('theme-toggle').addEventListener('click',()=>{document.body.classList.toggle('dark-mode');localStorage.setItem('darkMode',document.body.classList.contains('dark-mode'));});
document.querySelectorAll('.lang-btn').forEach(btn=>btn.addEventListener('click',()=>{currentLang=btn.dataset.lang;localStorage.setItem('lang',currentLang);translateApp();}));
document.querySelectorAll('.sidebar-menu li').forEach(li=>li.addEventListener('click',()=>{document.querySelectorAll('.sidebar-menu li').forEach(e=>e.classList.remove('active'));li.classList.add('active');document.querySelectorAll('.view-section').forEach(s=>s.classList.remove('active'));document.getElementById(li.dataset.view+'-view').classList.add('active');}));
});
const taskModal=document.getElementById('task-modal');const financeModal=document.getElementById('finance-modal');const interceptorModal=document.getElementById('interceptor-modal');
function openModal(modal){modal.classList.add('active');}function closeModal(modal){modal.classList.remove('active');}
document.querySelectorAll('.close-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.modal').forEach(m=>m.classList.remove('active'));}));
document.querySelectorAll('.add-task-btn').forEach(btn=>btn.addEventListener('click',()=>{taskModal.dataset.type=btn.dataset.type;document.getElementById('modal-title').textContent=btn.dataset.type==='daily'?'إضافة مهمة يومية':'إضافة مهمة';openModal(taskModal);}));
document.getElementById('save-task').addEventListener('click',()=>{const title=document.getElementById('task-title').value;const time=document.getElementById('task-time').value;const alert=document.getElementById('task-alert-type').value;if(!title)return;const type=taskModal.dataset.type||'daily';appData[currentAccount].tasks.push({id:Date.now(),title,time,alert,type,completed:false,inProgress:false});saveData();renderTasks();closeModal(taskModal);document.getElementById('task-title').value='';});
document.getElementById('quick-interceptor-btn').addEventListener('click',()=>openModal(interceptorModal));
document.getElementById('save-interceptor').addEventListener('click',()=>{const desc=document.getElementById('interceptor-desc').value;if(!desc)return;appData[currentAccount].interceptors.push({id:Date.now(),desc,time:new Date().toLocaleTimeString()});saveData();renderInterceptors();closeModal(interceptorModal);document.getElementById('interceptor-desc').value='';});
function renderTasks(){const list=document.getElementById('daily-tasks-list');list.innerHTML='';let completedCount=0;let totalCount=0;appData[currentAccount].tasks.filter(t=>t.type==='daily').forEach(task=>{if(task.completed)completedCount++;totalCount++;const div=document.createElement('div');div.className='task-item';div.innerHTML=`<div class="task-info"><div class="task-title">${task.title}</div><div class="task-time">${task.time||''} ${task.inProgress?'(قيد العمل)':''}</div></div><div class="task-actions"><button class="complete-btn" onclick="toggleComplete(${task.id})"><i class="fas fa-check"></i></button><button class="delete-btn" onclick="deleteTask(${task.id})"><i class="fas fa-trash"></i></button></div>`;list.appendChild(div);});const progress=totalCount>0?(completedCount/totalCount)*100:0;document.getElementById('daily-progress').style.width=progress+'%';document.getElementById('progress-percentage').textContent=Math.round(progress)+'%';}
function renderInterceptors(){const list=document.getElementById('daily-tasks-list');appData[currentAccount].interceptors.forEach(item=>{const div=document.createElement('div');div.className='task-item interceptor';div.innerHTML=`<div class="task-info"><div class="task-title">${item.desc}</div><div class="task-time">${item.time}</div></div><div class="task-actions"><button class="delete-btn" onclick="deleteInterceptor(${item.id})"><i class="fas fa-trash"></i></button></div>`;list.appendChild(div);});}
function toggleComplete(id){const task=appData[currentAccount].tasks.find(t=>t.id===id);if(task){task.completed=!task.completed;task.inProgress=false;saveData();renderTasks();}}
function deleteTask(id){appData[currentAccount].tasks=appData[currentAccount].tasks.filter(t=>t.id!==id);saveData();renderTasks();}
function deleteInterceptor(id){appData[currentAccount].interceptors=appData[currentAccount].interceptors.filter(i=>i.id!==id);saveData();renderTasks();}
document.querySelector('.add-finance-btn').addEventListener('click',()=>openModal(financeModal));
document.getElementById('save-finance').addEventListener('click',()=>{const desc=document.getElementById('finance-desc').value;const amount=parseFloat(document.getElementById('finance-amount').value);const type=document.getElementById('finance-type').value;if(!desc||!amount)return;appData[currentAccount].finance.push({id:Date.now(),desc,amount,type});saveData();renderFinance();closeModal(financeModal);document.getElementById('finance-desc').value='';document.getElementById('finance-amount').value='';});
function renderFinance(){const list=document.getElementById('finance-list');list.innerHTML='';let income=0;let expense=0;appData[currentAccount].finance.forEach(item=>{if(item.type==='income')income+=item.amount;else expense+=item.amount;const div=document.createElement('div');div.className='task-item';div.innerHTML=`<div class="task-info"><div class="task-title">${item.desc}</div><div class="task-time">${item.type==='income'?'وارد':'مصروف'}: ${item.amount}</div></div><div class="task-actions"><button class="delete-btn" onclick="deleteFinance(${item.id})"><i class="fas fa-trash"></i></button></div>`;list.appendChild(div);});document.getElementById('total-income').textContent=income;document.getElementById('total-expense').textContent=expense;}
function deleteFinance(id){appData[currentAccount].finance=appData[currentAccount].finance.filter(f=>f.id!==id);saveData();renderFinance();}
function renderCalendar(){const container=document.getElementById('calendar-container');container.innerHTML='';const date=new Date();const year=date.getFullYear();const month=date.getMonth();const firstDay=new Date(year,month,1).getDay();const daysInMonth=new Date(year,month+1,0).getDate();for(let i=0;i<firstDay;i++){const empty=document.createElement('div');empty.className='calendar-day empty';container.appendChild(empty);}for(let i=1;i<=daysInMonth;i++){const day=document.createElement('div');day.className='calendar-day';day.innerHTML=`<strong>${i}</strong>`;container.appendChild(day);}}
let myChart;function renderAnalytics(){const ctx=document.getElementById('charts-container');const completed=appData[currentAccount].tasks.filter(t=>t.completed).length;const pending=appData[currentAccount].tasks.filter(t=>!t.completed).length;if(myChart)myChart.destroy();const canvas=document.createElement('canvas');ctx.innerHTML='';ctx.appendChild(canvas);myChart=new Chart(canvas,{type:'doughnut',data:{labels:['مكتمل','معلق'],datasets:[{data:[completed,pending],backgroundColor:['#2ecc71','#e74c3c']}]}});}
renderTasks();renderInterceptors();renderFinance();renderCalendar();renderAnalytics();
document.getElementById('export-data').addEventListener('click',()=>{const dataStr=JSON.stringify(appData);const blob=new Blob([dataStr],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='life_app_backup.json';a.click();});
document.getElementById('import-data').addEventListener('click',()=>{const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=e=>{const file=e.target.files[0];const reader=new FileReader();reader.onload=ev=>{appData=JSON.parse(ev.target.result);saveData();renderTasks();renderFinance();renderAnalytics();};reader.readAsText(file);};input.click();});
document.getElementById('sync-cloud').addEventListener('click',()=>{alert('جارٍ المزامنة مع السحابة... تم الربط بالبريد الإلكتروني بنجاح!');});
document.getElementById('account-switcher').addEventListener('click',()=>{const email=prompt('أدخل البريد الإلكتروني للحساب:');if(email){currentAccount=email;localStorage.setItem('currentAccount',currentAccount);if(!appData[currentAccount])appData[currentAccount]={tasks:[],finance:[],interceptors:[]};saveData();renderTasks();renderInterceptors();renderFinance();renderAnalytics();}});
function checkAlerts(){const now=new Date();const currentTime=now.getHours()+':'+(now.getMinutes()<10?'0':'')+now.getMinutes();appData[currentAccount].tasks.forEach(task=>{if(task.time===currentTime&&!task.notified&&task.alert!=='none'){showNotification(task);task.notified=true;saveData();}});}
function showNotification(task){const container=document.getElementById('notification-container');const div=document.createElement('div');div.className=`notification ${task.alert}`;div.innerHTML=`<span>${task.title}</span><button class="close-notif" onclick="this.parentElement.remove()">&times;</button>`;container.appendChild(div);if(task.alert==='audio'||task.alert==='both'){const audio=new Audio('data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAAAAA=');audio.play();}setTimeout(()=>div.remove(),10000);}
setInterval(checkAlerts,60000);
